version: "3.7"

services:
  client:
    build:
      context: .
      args:
        - PORT=${PORT:-3001}
    image: ttt-img
    ports:
      - "80:${PORT:-3001}"
    container_name: ttt
    restart: unless-stopped
